package com.tradehero.th.utils.metrics.localytics;

public class LocalyticsConstants
{
    public static final String AppLaunch = "AppLaunch";
    public static final String TabBar_Me = "TabBar/Me";
    public static final String TabBar_Trade = "TabBar/Trade";
    public static final String TabBar_Trending = "TabBar/Trending";
    public static final String TabBar_Community = "TabBar/Community";
    public static final String TabBar_Portfolio = "TabBar/Portfolio";
    public static final String TabBar_Store = "TabBar/Store";
    public static final String TabBar_Settings = "TabBar/Settings";
    public static final String SignUp = "SignUp"; //User tap sign up on the landing
    public static final String SignUp_Tap = "SignUp/Tap"; //User tap sign up on the landing
    public static final String SignUp_Success = "SignUp/Success"; //User tap sign up on the landing
    public static final String SignIn = "SignIn"; //User tap sign in on the landing
    public static final String SignUp_Email = "SignUp/Email"; //User tap on sign up via email on
    public static final String Authentication_Facebook = "SignUp/Facebook"; // User tap on sign up via Facebook on sign up screen
    public static final String Authentication_LinkedIn = "SignUp/LinkedIn"; // User tap on sign up via LinkedIn
    public static final String Authentication_Twitter = "SignUp/Twitter"; // User tap on sign up via Twitter
    public static final String SignUp_Back = "SignUp/Back"; // User press back button on sign
    public static final String Settings_PayPal = "Settings/PayPal";
    public static final String Settings_Alipay = "Settings/Alipay";
    public static final String Settings_FAQ = "Settings/FAQ";
    public static final String Settings_TransactionHistory = "Settings/TransactionHistory";
    public static final String Referrals_Settings = "Referrals_Settings";
    public static final String Settings_About = "Settings/About";
    public static final String BuyCreditsDialog_Show = "BuyCreditsDialog/Show";
    public static final String BuyExtraCashDialog_Show = "BuyExtraCashDialog/Show";
    public static final String BuyStockAlertDialog_Show = "BuyStockAlertDialog/Show";
    public static final String ResetPortfolioDialog_Show = "ResetPortfolioDialog/Show";
    public static final String ResetPortfolioPopUp_Show = "ResetPortfolioPopUp/Show";
    public static final String ResetPortfolioPopUp_Buy = "ResetPortfolioPopUp/Buy";
    public static final String ResetPortfolio_Close = "ResetPortfolio/Close";
    public static final String LowCashPopUp_Show = "LowCashPopUp/Show";
    public static final String LowCashPopUp_Buy = "LowCashPopUp/Buy";
    public static final String LowCashPopUp_Close = "LowCashPopUp/Close";
    public static final String Heroes_BuyMoreCredits = "Heroes/BuyMoreCredits";// Anytime user buy more hero
    public static final String ExtraCash_BuySellScreen = "ExtraCash/BuySellScreen";// Buying extra cash on buy/sell
    public static final String StockAlerts_BuySellScreen = "StockAlerts/BuySellScreen";//
    public static final String StockAlerts_GetAlerts = "StockAlerts/GetAlerts";// Buy stock alerts IAP
    public static final String SearchResult_Stock = "SearchResult/Stock";// stock NASDAQ:AA
    public static final String SearchResult_User = "SearchResult/User";// user
    public static final String Watchlist_List = "Watchlist/List";//
    public static final String Watchlist_Edit = "Watchlist/Edit";// symbol security.qualiﬁ
    public static final String Watchlist_Add = "Watchlist/Add";// symbol security.qualiﬁ
    public static final String Watchlist_Delete = "Watchlist/Delete";// symbol deletedPositio
    public static final String Watchlist_CellSwipe = "Watchlist/CellSwipe";// symbol self.security.q
    public static final String Watchlist_More_Tap = "Watchlist/More/Tap";// symbol self.security.q
    public static final String Positions_Follow = "Positions/Follow";// Following user from positions
    public static final String Position_CellSwipe = "Position/CellSwipe";// symbol
    public static final String Position_More_Tap = "Position/More/Tap";// symbol
    public static final String Leaderboards_ShowLeaderboard = "Leaderboards/ShowLeaderboard";//
    public static final String Leaderboard_Profile = "Leaderboard/Profile";// Tap proﬁle on leaderboard user
    public static final String Leaderboard_Positions = "Leaderboard/Positions";// Tap positins on leaderboard user
    public static final String Leaderboard_Follow = "Leaderboard/Follow";// Tap follow on leaderboard user
    public static final String Leaderboard_Back = "Leaderboard/Back";// Tap back on leaderboard leaderboardId
    public static final String Leaderboard_FilterShow = "Leaderboard/FilterShow";// Leaderboard ﬁlter screen is
    public static final String Leaderboard_FilterChange = "Leaderboard/FilterChange";//
    public static final String Leaderboard_FilterCancel = "Leaderboard/FilterCancel";// User tap cancel on leaderboard
    public static final String Leaderboard_FilterReset = "Leaderboard/FilterReset";// User tap reset on leaderboard
    public static final String Leaderboard_FilterDone = "Leaderboard/FilterDone";//
    public static final String FriendsLeaderboard_Filter_FoF = "FriendsLeaderboard/Filter/FoF";//
    public static final String Leaderboards_DrillDown = "Leaderboards/DrillDown";// User tap on leaderboard under
    public static final String Security_TapChartPeriod_Landscape = "Security/TapChartPeriod/Landscape";//
    public static final String Security_TapChartPeriod_Portrait = "Security/TapChartPeriod/Portrait";//
    public static final String Security_TapPrice = "Security/TapPrice";// symbol self.security.q
    public static final String Security_RotateToLandscapeChart ="Security/RotateToLandscapeChart";//
    public static final String Security_NewDiscussion = "Security/NewDiscussion";// symbol self.security.q
    public static final String Security_Tab_Discussion = "Security/Tab/Discussion";// symbol self.security.q
    public static final String Security_Tab_News = "Security/Tab/News";// symbol self.security.q
    public static final String Security_Tab_Info = "Security/Tab/Info";// symbol self.security.q
    public static final String Proﬁle_Tab_Timeline = "Proﬁle/Tab/Timeline";//
    public static final String Proﬁle_Follow = "Proﬁle/Follow";//
    public static final String Notification_New_Message = "Notification/NewMessgae";//
    public static final String Notification_New_Broadcast = "Notification/NewBroadcast";//
    public static final String Proﬁle_Tab_Portfolios = "Proﬁle/Tab/Portfolios";// Portfolios tab is shown on user
    public static final String Proﬁle_Tab_Stats = "Proﬁle/Tab/Stats";// Stats tab
    public static final String Monitor_Show = "Monitor/Show";// source
    public static final String Monitor_Cancel = "Monitor/Cancel";// source
    public static final String Monitor_EditWatchlist = "Monitor/EditWatchlist";// source
    public static final String Monitor_CreateWatchlist = "Monitor/CreateWatchlist";// source
    public static final String Monitor_Alert = "Monitor/Alert";// source
    public static final String Monitor_Chart = "Monitor/Chart";// source
    public static final String Monitor_BuySell = "Monitor/BuySell";// source
    public static final String Monitor_TradeHistory = "Monitor/TradeHistory";// source
    public static final String StockAlerts_Save = "StockAlerts/Save";// Saving stock alert on stock alert
    public static final String TrendingStock = "TrendingStock"; // Tapping on a stock item in Trending screen
    public static final String BuySellPanel_Chart = "BuySellPanel/Chart_%s"; // Open the buy sell screen with a chart
    public static final String PickChart = "PickChart/%s"; // Changing a chart
    public static final String Trade_Buy = "Trade/Buy";// on transaction screen symbol
    public static final String Trade_Sell = "Trade/Sell";//

    public static final String BroadcastAllFollowers = "Broadcast All Followers";//
    public static final String BroadcastFreeFollowers = "Broadcast Free Followers";//
    public static final String BroadcastPremiumFollowers = "Broadcast Premium Followers";//
    public static final String Email = "Email";//
    public static final String Facebook = "Facebook";//
    public static final String InviteFriends = "InviteFriends";//
    public static final String Linkedin = "Linkedin";//
    public static final String Loading = "Loading";//
    public static final String LoadingScreen = "LoadingScreen";//
    public static final String Login_Form = "LoginForm";//
    public static final String LoginFormScreen = "LoginFormScreen";//
    public static final String Login_Register = "Login/Register";//
    public static final String LoginRegisterScreen = "LoginRegisterScreen";//
    public static final String MessageComposer_Show = "MessageComposer/Show";//
    public static final String MessageComposer_Send = "MessageComposer/Send";//
    public static final String PrivateMessage = "Private Message";//
    public static final String QQ = "QQ";//
    public static final String Register_Form = "RegisterForm";//
    public static final String RegisterFormScreen = "RegisterFormScreen";//
    public static final String Screen = "Screen ";//
    public static final String Splash = "Splash";//
    public static final String SplashScreen = "SplashScreen";//
    public static final String SplashScreenCancel = "SplashScreenCancel";//
    public static final String Twitter = "Twitter";//
    public static final String WeiBo = "WeiBo";//

    //public static final String CHANNEL_MAP_KEY = "channel";
    public static final String METHOD_MAP_KEY = "method";
    public static final String SECURITY_SYMBOL_MAP_KEY = "symbol";
    public static final String TRENDING_FILTER_CATEGORY_MAP_KEY = "category";
    public static final String TYPE_MAP_KEY = "type";
}
